apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-monitoring.yaml
  - weave-gitops-podmonitor.yaml
configMapGenerator:
  - name: weave-gitops-grafana-dashboards
    files:
      - dashboards/overview.json
      - dashboards/explorer.json
      - dashboards/runtime.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
