apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: flux
  name: weave-gitops
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  podMetricsEndpoints:
    - port: http-metrics
    - port: monitoring
    - port: metrics
    - port: http-prom
  selector:
    matchExpressions:
      - key: app.kubernetes.io/part-of
        operator: In
        values:
          - weave-gitops
